# Numpy is a library built over Mathematics,Data Structures, Statistical Funcs,Linear Expressions
# arange--- generates range of elements in an array
# # follows n-1 rule of right index
# parameter inbuild model
# hypermeter-->user changed in machine learning
# hyperparameter tuning is called as finetune in llm
 # randint(a,b) returns random btw a and b --a inclusive and b exclusive
 # randint(2,100,10)  random 10 no. btw 2 and 100 2 inclusive 100 exclusive

In [1]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.


In [20]:
import numpy as np
np.__version__

'1.26.4'

In [21]:
my_list=[0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [22]:
type(my_list)

list

In [25]:
arr=np.array(my_list)  #list to array
print(type(arr))
print(arr)


<class 'numpy.ndarray'>
[0 1 2 3 4 5]


In [27]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [28]:
np.arange(5.0)

array([0., 1., 2., 3., 4.])

In [29]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [30]:
np.arange(10,19)

array([10, 11, 12, 13, 14, 15, 16, 17, 18])

In [31]:
np.arange(20,10)

array([], dtype=int32)

In [32]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [34]:
np.arange(-20,-10)  

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11])

In [37]:
ar=np.arange(-30,20)
print(ar)

[-30 -29 -28 -27 -26 -25 -24 -23 -22 -21 -20 -19 -18 -17 -16 -15 -14 -13
 -12 -11 -10  -9  -8  -7  -6  -5  -4  -3  -2  -1   0   1   2   3   4   5
   6   7   8   9  10  11  12  13  14  15  16  17  18  19]


In [39]:
np.arange(10,10)

array([], dtype=int32)

In [40]:
np.arange(10,30,5)  # as per n-1 rule 30-1 is 29 so 30 is not printed

array([10, 15, 20, 25])

In [44]:
np.zeros(5)   #1d Array  #dtype=int is parameter tuning--->

array([0., 0., 0., 0., 0.])

In [45]:
np.zeros(5,dtype=int)  

array([0, 0, 0, 0, 0])

In [46]:
np.zeros(5,dtype=int)   #dtype=int is hyper parameter tuning--->as we are changing to our required data type

array([0., 0., 0., 0., 0.])

In [48]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [49]:
np.zeros((2,10),dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [50]:
np.zeros((10,30),dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [51]:
np.ones(3)

array([1., 1., 1.])

In [52]:
np.ones(3,dtype=int)

array([1, 1, 1])

In [55]:
n=2
np.ones((n),dtype=int)

array([1, 1])

In [69]:
np.random.rand(3,2)  #np package  random is module and rand is func

array([[0.43362431, 0.91225118],
       [0.7664991 , 0.68666458],
       [0.74646935, 0.87163606]])

In [71]:
np.random.rand(2,4)

array([[0.25679941, 0.85293101, 0.10735546, 0.10765255],
       [0.83249332, 0.40476219, 0.4695379 , 0.87710654]])

In [81]:
np.random.randint(2,4)  # randint(a,b) returns random btw a and b --a inclusive and b exclusive

3

In [95]:
np.random.randint(2,100)

23

In [96]:
np.random.randint(2,100,10)

array([85, 56,  3, 89, 29, 97, 40, 70, 72, 18])

In [97]:
np.random.randint(-30,100,10)

array([ 50, -19, -26,  51,  15,  -7,  89,  52,  48, -21])

In [100]:
np.random.randint(-1)

ValueError: high <= 0

In [17]:
import numpy as np

# Creating a 1D array
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)




[1 2 3 4 5]


In [19]:
import numpy as np


# Creating a 2D array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)
arr3=arr2[0,1]  # row by column
print(arr3)



[[1 2 3]
 [4 5 6]]
2


In [12]:
import numpy as np

# Creating an array of zeros
zeros = np.zeros((3, 3))
print(zeros)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [14]:
import numpy as np

# Creating an array of ones
ones = np.ones((2, 2))
print(ones)

[[1. 1.]
 [1. 1.]]


In [15]:
import numpy as np

# Creating an array with a range
range_arr = np.arange(1, 10, 2)  # [1, 3, 5, 7, 9]
print(range_arr)

[1 3 5 7 9]


In [16]:
import numpy as np

# Creating an array with random values
random_arr = np.random.rand(3, 3)
print(random_arr)


[[0.15152124 0.90988486 0.76596969]
 [0.91441178 0.48831733 0.33436859]
 [0.27509184 0.17798604 0.93870906]]
