# Numpy is a library built over Mathematics,Data Structures, Statistical Funcs,Linear Expressions
# arange--- generates range of elements in an array
# # follows n-1 rule of right index
# parameter inbuild model
# hypermeter-->user changed in machine learning
# hyperparameter tuning is called as finetune in llm
 # randint(a,b) returns random btw a and b --a inclusive and b exclusive
 # randint(2,100,10)  random 10 no. btw 2 and 100 2 inclusive 100 exclusive

In [115]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np
np.__version__

'1.26.4'

In [117]:
my_list=[0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [118]:
type(my_list)

list

In [119]:
arr=np.array(my_list)  #list to array
print(type(arr))
print(arr)


<class 'numpy.ndarray'>
[0 1 2 3 4 5]


In [120]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [121]:
np.arange(5.0)

array([0., 1., 2., 3., 4.])

In [122]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [123]:
np.arange(10,19)

array([10, 11, 12, 13, 14, 15, 16, 17, 18])

In [124]:
np.arange(20,10)

array([], dtype=int32)

In [125]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [126]:
np.arange(-20,-10)  

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11])

In [127]:
ar=np.arange(-30,20)
print(ar)

[-30 -29 -28 -27 -26 -25 -24 -23 -22 -21 -20 -19 -18 -17 -16 -15 -14 -13
 -12 -11 -10  -9  -8  -7  -6  -5  -4  -3  -2  -1   0   1   2   3   4   5
   6   7   8   9  10  11  12  13  14  15  16  17  18  19]


In [128]:
np.arange(10,10)

array([], dtype=int32)

In [129]:
np.arange(10,30,5)  # as per n-1 rule 30-1 is 29 so 30 is not printed

array([10, 15, 20, 25])

In [130]:
np.zeros(5)   #1d Array  #dtype=int is parameter tuning--->

array([0., 0., 0., 0., 0.])

In [131]:
np.zeros(5,dtype=int)  

array([0, 0, 0, 0, 0])

In [132]:
np.zeros(5,dtype=int)   #dtype=int is hyper parameter tuning--->as we are changing to our required data type

array([0, 0, 0, 0, 0])

In [133]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [134]:
np.zeros((2,10),dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [135]:
np.zeros((10,30),dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [136]:
np.ones(3)

array([1., 1., 1.])

In [137]:
np.ones(3,dtype=int)

array([1, 1, 1])

In [138]:
n=2
np.ones((n),dtype=int)

array([1, 1])

In [139]:
np.random.rand(3,2)  #np package  random is module and rand is func

array([[2.15761602e-01, 4.78919686e-01],
       [7.11864331e-06, 1.60095342e-01],
       [8.08345818e-01, 9.85817206e-01]])

In [140]:
np.random.rand(2,4)

array([[0.73880352, 0.26217952, 0.859846  , 0.31503336],
       [0.35388396, 0.74443746, 0.29095072, 0.7548551 ]])

In [141]:
np.random.randint(2,4)  # randint(a,b) returns random btw a and b --a inclusive and b exclusive

2

In [142]:
np.random.randint(2,100)

91

In [143]:
np.random.randint(2,100,10)

array([91, 85, 73, 96, 51, 85, 63, 38, 26, 92])

In [144]:
np.random.randint(-30,100,10)

array([ 43,  82, -30, -10,  -3,  28,  58,  97,  57,  87])

In [145]:
np.random.randint(-1)

ValueError: high <= 0

# 04-02-2025

In [8]:
import numpy as np


In [7]:
np.random.randint(20,40,5)

array([33, 30, 27, 28, 23])

In [9]:
np.random.randint(20,40,(10,10)) # range btw 20 and 40 10 by 10 array 20 included,40 excluded

array([[24, 22, 28, 28, 30, 28, 31, 37, 28, 22],
       [39, 28, 38, 39, 39, 37, 32, 38, 39, 34],
       [35, 30, 25, 33, 22, 31, 21, 37, 22, 36],
       [30, 25, 30, 39, 25, 28, 28, 20, 21, 24],
       [28, 29, 36, 20, 29, 26, 35, 28, 28, 39],
       [33, 33, 34, 35, 34, 37, 35, 29, 35, 25],
       [38, 28, 33, 36, 22, 28, 25, 32, 24, 31],
       [30, 26, 25, 37, 28, 25, 23, 32, 25, 21],
       [22, 39, 32, 20, 38, 29, 25, 35, 22, 28],
       [27, 32, 35, 24, 21, 35, 27, 32, 32, 30]])

In [10]:
np.random.randint(1,400,(20,10))

array([[259, 314, 236, 337, 147, 110, 102, 178, 186,  90],
       [151,   2, 168,  50, 318, 142,   1, 283, 212, 293],
       [377, 238, 340,  79, 236, 387, 206, 283, 107, 357],
       [266, 197, 223, 113, 149,  60, 394, 324,  35,  16],
       [240, 131, 338, 298,  41, 170, 134, 357, 218, 183],
       [304,  43, 250, 323, 130, 193, 391, 257, 219, 119],
       [202,  80, 301, 380, 381, 381,  27, 382, 213, 363],
       [225, 170, 304, 303, 280, 221, 145,  46, 323, 366],
       [202,  21, 322, 317, 240,  34,   1, 213, 157, 159],
       [139, 299, 271, 116, 212, 146, 342,   5,  39, 101],
       [  4, 135, 180, 118, 149, 225, 323, 271, 213, 329],
       [174, 105, 109,   9,  77, 131, 336, 123, 107, 278],
       [ 17, 111, 139, 314,  19, 390, 176, 151, 231, 283],
       [ 83,  22, 290, 231, 248, 354,  16, 163, 203, 391],
       [231, 329,  37, 312, 397, 330, 236, 112, 172, 316],
       [ 40,  93, 148, 101,  50, 145, 305, 394, 141, 230],
       [261,  79, 325, 265, 321, 234, 357,  51, 258, 289

In [12]:
np.arange(1,13)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [13]:
np.arange(1,13).reshape(3,4)  # above array is rearanged as 3 by 4 matrix

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [14]:
np.arange(1,13).reshape(3,5)  # error as sufficient elements are not available

ValueError: cannot reshape array of size 12 into shape (3,5)

In [15]:
np.arange(1,13).reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [17]:
np.arange(1,13).reshape(12,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [18]:
np.arange(1,13).reshape(1,12)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

# slicing in Matrix

In [151]:
b=np.random.randint(10,40,(5,4))

In [14]:
b

array([[18, 17, 11, 12],
       [21, 22, 26, 39],
       [25, 32, 17, 26],
       [17, 34, 33, 36],
       [17, 35, 10, 21]])

In [15]:
b[:]

array([[18, 17, 11, 12],
       [21, 22, 26, 39],
       [25, 32, 17, 26],
       [17, 34, 33, 36],
       [17, 35, 10, 21]])

In [16]:
b[4:]  # returns 4th row

array([[17, 35, 10, 21]])

In [17]:
b[1:3]  # # returns 1 index to n-1 index

array([[21, 22, 26, 39],
       [25, 32, 17, 26]])

In [18]:
b[1,3]  # 1st row 3rd element  here also slicing follows same rules as in list

39

In [20]:
b[1,-1] # when want to retrieve element in specific pos then we use ","(Comma) and then the 2nd param is used to retirve the pos of which elemnt in that col

39

In [21]:
b[3,-2]

33

In [22]:
b

array([[18, 17, 11, 12],
       [21, 22, 26, 39],
       [25, 32, 17, 26],
       [17, 34, 33, 36],
       [17, 35, 10, 21]])

In [24]:
b[2:4]  # when slice is there whole row comes .Slicing works as n-1 index from  right side

array([[25, 32, 17, 26],
       [17, 34, 33, 36]])

In [25]:
b

array([[18, 17, 11, 12],
       [21, 22, 26, 39],
       [25, 32, 17, 26],
       [17, 34, 33, 36],
       [17, 35, 10, 21]])

In [27]:
b[-4,-2]  # when -ve value is used for finding element then rows start from down most col and columns starts from right most col.her n-1 tule donot apply

26

In [28]:
b[-2,-3]

34

In [29]:
b[:4]  # since its slicing n-1 ruule applies

array([[18, 17, 11, 12],
       [21, 22, 26, 39],
       [25, 32, 17, 26],
       [17, 34, 33, 36]])

In [30]:
b

array([[18, 17, 11, 12],
       [21, 22, 26, 39],
       [25, 32, 17, 26],
       [17, 34, 33, 36],
       [17, 35, 10, 21]])

In [32]:
b[:-3] # starting to n-1 rule applies here

array([[18, 17, 11, 12],
       [21, 22, 26, 39]])

In [33]:
b

array([[18, 17, 11, 12],
       [21, 22, 26, 39],
       [25, 32, 17, 26],
       [17, 34, 33, 36],
       [17, 35, 10, 21]])

In [34]:
b[::-1]  #reverses the matrix as 1st row to last and last row to 1st

array([[17, 35, 10, 21],
       [17, 34, 33, 36],
       [25, 32, 17, 26],
       [21, 22, 26, 39],
       [18, 17, 11, 12]])

In [35]:
b

array([[18, 17, 11, 12],
       [21, 22, 26, 39],
       [25, 32, 17, 26],
       [17, 34, 33, 36],
       [17, 35, 10, 21]])

In [36]:
b[::-2]  

array([[17, 35, 10, 21],
       [25, 32, 17, 26],
       [18, 17, 11, 12]])

In [38]:
b[::2]  

array([[18, 17, 11, 12],
       [25, 32, 17, 26],
       [17, 35, 10, 21]])

In [39]:
b

array([[18, 17, 11, 12],
       [21, 22, 26, 39],
       [25, 32, 17, 26],
       [17, 34, 33, 36],
       [17, 35, 10, 21]])

In [40]:
b[::-3]

array([[17, 35, 10, 21],
       [21, 22, 26, 39]])

In [42]:
b=np.random.randint(1,100,(10,10))

In [43]:
b

array([[25, 50, 63,  2, 27, 50, 54, 84, 90, 94],
       [21, 91, 98, 56, 56, 47, 37, 54, 43, 95],
       [55, 22, 90,  7, 16, 95, 24, 66, 70, 55],
       [95,  7, 57, 58, 24, 75, 54, 58, 64, 66],
       [69, 32,  2, 20,  2, 45, 89, 64, 65, 56],
       [ 1, 52, 79,  9, 56, 71, 66, 16, 83, 31],
       [50, 46,  1,  7, 68, 81, 72, 44, 36, 57],
       [32,  2, 45, 14, 34, 73, 21, 60, 58, 91],
       [19, 29, 16, 11, 67, 21, 82, 84, 57, 90],
       [64, 17,  1, 38, 49, 99, 55, 20, 79, 20]])

In [44]:

b[:-3]

array([[25, 50, 63,  2, 27, 50, 54, 84, 90, 94],
       [21, 91, 98, 56, 56, 47, 37, 54, 43, 95],
       [55, 22, 90,  7, 16, 95, 24, 66, 70, 55],
       [95,  7, 57, 58, 24, 75, 54, 58, 64, 66],
       [69, 32,  2, 20,  2, 45, 89, 64, 65, 56],
       [ 1, 52, 79,  9, 56, 71, 66, 16, 83, 31],
       [50, 46,  1,  7, 68, 81, 72, 44, 36, 57]])

In [147]:
b

array([[7, 7, 1, 7, 4],
       [3, 4, 1, 1, 3]])

In [149]:
b[3:]

array([], shape=(0, 5), dtype=int32)

In [46]:
b

array([[25, 50, 63,  2, 27, 50, 54, 84, 90, 94],
       [21, 91, 98, 56, 56, 47, 37, 54, 43, 95],
       [55, 22, 90,  7, 16, 95, 24, 66, 70, 55],
       [95,  7, 57, 58, 24, 75, 54, 58, 64, 66],
       [69, 32,  2, 20,  2, 45, 89, 64, 65, 56],
       [ 1, 52, 79,  9, 56, 71, 66, 16, 83, 31],
       [50, 46,  1,  7, 68, 81, 72, 44, 36, 57],
       [32,  2, 45, 14, 34, 73, 21, 60, 58, 91],
       [19, 29, 16, 11, 67, 21, 82, 84, 57, 90],
       [64, 17,  1, 38, 49, 99, 55, 20, 79, 20]])

In [48]:
b[::-3] 

array([[64, 17,  1, 38, 49, 99, 55, 20, 79, 20],
       [50, 46,  1,  7, 68, 81, 72, 44, 36, 57],
       [95,  7, 57, 58, 24, 75, 54, 58, 64, 66],
       [25, 50, 63,  2, 27, 50, 54, 84, 90, 94]])

In [54]:
b

array([[25, 50, 63,  2, 27, 50, 54, 84, 90, 94],
       [21, 91, 98, 56, 56, 47, 37, 54, 43, 95],
       [55, 22, 90,  7, 16, 95, 24, 66, 70, 55],
       [95,  7, 57, 58, 24, 75, 54, 58, 64, 66],
       [69, 32,  2, 20,  2, 45, 89, 64, 65, 56],
       [ 1, 52, 79,  9, 56, 71, 66, 16, 83, 31],
       [50, 46,  1,  7, 68, 81, 72, 44, 36, 57],
       [32,  2, 45, 14, 34, 73, 21, 60, 58, 91],
       [19, 29, 16, 11, 67, 21, 82, 84, 57, 90],
       [64, 17,  1, 38, 49, 99, 55, 20, 79, 20]])

In [55]:
b[-4,-2]

36

In [56]:
from numpy import *
median(b)

54.0

In [57]:
np.median(b)

54.0

In [49]:
b.min()

1

In [50]:
b.mean()

49.13

In [53]:
b.max()

99

In [58]:
b

array([[25, 50, 63,  2, 27, 50, 54, 84, 90, 94],
       [21, 91, 98, 56, 56, 47, 37, 54, 43, 95],
       [55, 22, 90,  7, 16, 95, 24, 66, 70, 55],
       [95,  7, 57, 58, 24, 75, 54, 58, 64, 66],
       [69, 32,  2, 20,  2, 45, 89, 64, 65, 56],
       [ 1, 52, 79,  9, 56, 71, 66, 16, 83, 31],
       [50, 46,  1,  7, 68, 81, 72, 44, 36, 57],
       [32,  2, 45, 14, 34, 73, 21, 60, 58, 91],
       [19, 29, 16, 11, 67, 21, 82, 84, 57, 90],
       [64, 17,  1, 38, 49, 99, 55, 20, 79, 20]])

In [61]:
b=np.random.randint(1,10,(2,5))

In [62]:
b

array([[7, 7, 1, 7, 4],
       [3, 4, 1, 1, 3]])

In [65]:
b.reshape(2,5,order="C")

array([[7, 7, 1, 7, 4],
       [3, 4, 1, 1, 3]])

In [66]:
b.reshape(2,5,order="F")

array([[7, 7, 1, 7, 4],
       [3, 4, 1, 1, 3]])

In [67]:
b.reshape(2,5,order="A")

array([[7, 7, 1, 7, 4],
       [3, 4, 1, 1, 3]])

In [4]:
mat=np.arange(0,100).reshape(10,10)

In [69]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [73]:
row=4
col=5
mat[row,col]


45

In [74]:
mat[6]

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [75]:
mat[6,2] # 6th row col 2 index starts from 0

62

In [77]:
mat[9,2]

92

In [156]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [155]:
mat[row,:]

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [84]:
mat[row,6]

46

In [102]:
mat

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [87]:
mat[2:6,2:4]

array([[22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])

In [88]:
mat[2:3,2:3]

array([[22]])

In [89]:
mat[2:4,3:5]

array([[23, 24],
       [33, 34]])

In [97]:
mat=np.arange(0,100).reshape(10,10)


In [111]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [112]:
mat[2,3]

23

In [114]:
mat[2:5,3:5]

array([[23, 24],
       [33, 34],
       [43, 44]])

In [105]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [106]:
mat<50

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [108]:
mat[mat<=50] # all logical ops can be applied on mat[mat]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [110]:
mat[mat!=50]  # filters

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [157]:
mat


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [160]:
mat.reshape(20,5,order="C")

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]])

In [165]:
mat.reshape(20,5,order="F")

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48],
       [50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68],
       [70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88],
       [90, 92, 94, 96, 98],
       [ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49],
       [51, 53, 55, 57, 59],
       [61, 63, 65, 67, 69],
       [71, 73, 75, 77, 79],
       [81, 83, 85, 87, 89],
       [91, 93, 95, 97, 99]])

In [162]:
mat.reshape(20,5,order="A")

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]])

In [17]:
import numpy as np

# Creating a 1D array
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)




[1 2 3 4 5]


In [19]:
import numpy as np


# Creating a 2D array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)
arr3=arr2[0,1]  # row by column
print(arr3)



[[1 2 3]
 [4 5 6]]
2


In [12]:
import numpy as np

# Creating an array of zeros
zeros = np.zeros((3, 3))
print(zeros)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [14]:
import numpy as np

# Creating an array of ones
ones = np.ones((2, 2))
print(ones)

[[1. 1.]
 [1. 1.]]


In [15]:
import numpy as np

# Creating an array with a range
range_arr = np.arange(1, 10, 2)  # [1, 3, 5, 7, 9]
print(range_arr)

[1 3 5 7 9]


In [16]:
import numpy as np

# Creating an array with random values
random_arr = np.random.rand(3, 3)
print(random_arr)


[[0.15152124 0.90988486 0.76596969]
 [0.91441178 0.48831733 0.33436859]
 [0.27509184 0.17798604 0.93870906]]


In [5]:
mat=np.arange(0,100).reshape(10,10)


In [6]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [7]:
mat.reshape(20,5,order="C")

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]])

In [11]:
mat.reshape(20,5,order="F")

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48],
       [50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68],
       [70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88],
       [90, 92, 94, 96, 98],
       [ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49],
       [51, 53, 55, 57, 59],
       [61, 63, 65, 67, 69],
       [71, 73, 75, 77, 79],
       [81, 83, 85, 87, 89],
       [91, 93, 95, 97, 99]])

In [13]:
b=np.random.randint(10,40,(5,4))
b

array([[18, 17, 11, 12],
       [21, 22, 26, 39],
       [25, 32, 17, 26],
       [17, 34, 33, 36],
       [17, 35, 10, 21]])